version: '3.3'

services:
  orangehrm:
    image: orangehrm/orangehrm:latest
    ports:
      - "8080:80"
    environment:
      - ORANGEHRM_DATABASE_HOST=db
      - ORANGEHRM_DATABASE_USER=orangehrm
      - ORANGEHRM_DATABASE_PASSWORD=orangehrm
      - ORANGEHRM_DATABASE_NAME=orangehrm
    depends_on:
      - db

  db:
    image: mysql:8.0.43-debian
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=orangehrm
      - MYSQL_PASSWORD=orangehrm
      - MYSQL_DATABASE=orangehrm
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
